workflows:
  android-release:
    name: Android Release Workflow
    environment:
      vars:
        # Add any secrets here if needed (API keys, keystore password)
      flutter: stable
      xcode: latest
      cocoapods: default
      android:
        gradle-args: "--no-daemon"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Run Flutter analyze
        script: |
          flutter analyze
      - name: Run Flutter tests
        script: |
          flutter test
      - name: Build Android Release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        on_success: always
        on_failure: always
