workflows:
  android_debug_build:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: none
      vars:
        FLUTTER_BUILD_MODE: debug
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - amiin@example.com
        on_success: always
        on_failure: always
