workflows:
  android-build:
    name: Build eMaamul Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      android: latest
    scripts:
      # --- Fix flutter_barcode_scanner plugin namespace (Groovy style) ---
      - name: Fix flutter_barcode_scanner namespace
        script: |
          PLUGIN_DIR="$FLUTTER_ROOT/.pub-cache/hosted/pub.dev/flutter_barcode_scanner-2.0.0/android"
          if [ -f "$PLUGIN_DIR/build.gradle" ]; then
            echo "⚙️ Adding namespace to flutter_barcode_scanner..."
            echo "namespace 'com.amindev.flutter_barcode_scanner'" >> "$PLUGIN_DIR/build.gradle"
            echo "✅ Namespace added to flutter_barcode_scanner"
          else
            echo "⚠️ flutter_barcode_scanner plugin not found, skipping."
          fi

      # --- Fix Kotlin DSL build.gradle.kts syntax if exists ---
      - name: Patch app/build.gradle.kts
        script: |
          APP_GRADLE="android/app/build.gradle.kts"
          if [ -f "$APP_GRADLE" ]; then
            echo "⚙️ Patching Kotlin DSL namespace..."
            sed -i '' '/android {/a\
              namespace = "com.emaamul.app"\
            ' "$APP_GRADLE"
            echo "✅ Kotlin DSL namespace added"
          fi

      # --- Clean and fetch dependencies ---
      - name: Flutter clean and pub get
        script: |
          flutter clean
          flutter pub get

      # --- Build Android Release APK ---
      - name: Build Android Release APK
        script: |
          flutter build apk --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - amiin4dm@gmail.com
