name: emaamulapp
description: A QuickBooks-like Flutter app for small businesses
publish_to: "none" # private project

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0  # Or the latest compatible version

  # Firebase - Using compatible versions for current Flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4

  # State management
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9

  # UI and Charts
  fl_chart: ^0.66.0

  # Barcode Scanner (disabled for web compatibility)
  # flutter_barcode_scanner: ^2.0.0

  # HTTP requests
  http: ^1.1.2

  # Utilities
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
