// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfihRhW5pQs438Yzuh1t8g-HzwBW982MY',
    appId: '1:615814131455:web:f1231b30633762bd83e6ca',
    messagingSenderId: '615814131455',
    projectId: 'appdata-3966a',
    authDomain: 'appdata-3966a.firebaseapp.com',
    storageBucket: 'appdata-3966a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3Y2QvFyI7WSvonJT5KC82v0jczFmXyc',
    appId: '1:615814131455:android:a8bab322d3263bcd83e6ca',
    messagingSenderId: '615814131455',
    projectId: 'appdata-3966a',
    storageBucket: 'appdata-3966a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwb1RefaIqWwhLA3oTiMjDi120CjsTyfk',
    appId: '1:615814131455:ios:dab73d6392c1c34983e6ca',
    messagingSenderId: '615814131455',
    projectId: 'appdata-3966a',
    storageBucket: 'appdata-3966a.firebasestorage.app',
    iosBundleId: 'com.example.emaamulapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwb1RefaIqWwhLA3oTiMjDi120CjsTyfk',
    appId: '1:615814131455:ios:dab73d6392c1c34983e6ca',
    messagingSenderId: '615814131455',
    projectId: 'appdata-3966a',
    storageBucket: 'appdata-3966a.firebasestorage.app',
    iosBundleId: 'com.example.emaamulapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfihRhW5pQs438Yzuh1t8g-HzwBW982MY',
    appId: '1:615814131455:web:2a6b71639fa9f7f283e6ca',
    messagingSenderId: '615814131455',
    projectId: 'appdata-3966a',
    authDomain: 'appdata-3966a.firebaseapp.com',
    storageBucket: 'appdata-3966a.firebasestorage.app',
  );
}
